### ISSUE TITLE
Question: minimum JDK version

### ISSUE THREAD

**Issue by nlmills** [MonALISA-CIT/fdt#7]
What version of the JDK will be required to run the next version of FDT? I would like to know what features I can use in new code.

Thanks,
Nick

**Comment by juztas** [comment]
Currently it is 1.6. Maybe we could chat what other improvements you think about and we could see how we could proceed and are we changing JDK version to support new features.

**Comment by nlmills** [comment]
No, I don't have any arguments yet for changing the version. I just wanted to avoid using unsupported features in future pull requests. Thanks!
